name: "build"
on: [push, pull_request]
jobs:
    deploy:
        # Specify runner + deployment step
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.4.3
              with:
                branch: gh-pages
                folder: .